### ISSUE TITLE
The Package isn’t working 

### ISSUE THREAD

**Issue by ibrafayez** [pacifio/aurora#1]
When I add the dependency in the pubspec.yaml file the following error appears:

```
Error on line 31, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
31 │   aurora: ^0.0.1
   │   ^^^^^^
   ╵
pub get failed (65;    ╵)
```

Regards

**Comment by pacifio** [comment]
I think your `pubspec.yaml` has the name field set like this

`name: aurora`

You need to change this to something else as you cannot have a same named project and a library
